apiVersion: v1
kind: Service
metadata:
  name: python-web-service
spec:
  type: LoadBalancer  # This exposes it to your actual computer (localhost)
  selector:
    app: my-web-app   # Connects this service to your "my-web-app" pods
  ports:
    - protocol: TCP
      port: 5000      # The port you visit in the browser
      targetPort: 5000 # The port the container is listening on